//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKING()
        {
            this.CUSTOMER_PAYMENT_RECEIPT = new HashSet<CUSTOMER_PAYMENT_RECEIPT>();
        }
    
        public int ID_BOOKING { get; set; }
        public int ID_PITCH { get; set; }
        public int CREATE_BY_ID_USER { get; set; }
        public System.DateTime CREATE_AT { get; set; }
        public Nullable<int> UPDATE_BY_ID_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public bool IS_DELETED { get; set; }
        public string COST { get; set; }
        public string CHECK_IN_TIME { get; set; }
        public string CHECK_OUT_TIME { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_PHONE_NUMBER { get; set; }
        public string DATE_BOOKING { get; set; }
        public string IS_DONE { get; set; }
    
        public virtual PITCH PITCH { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PAYMENT_RECEIPT> CUSTOMER_PAYMENT_RECEIPT { get; set; }
    }
}
