//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMODITIES_PROVIDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMODITIES_PROVIDER()
        {
            this.IMPORT_COMMODITIES_RECEIPT = new HashSet<IMPORT_COMMODITIES_RECEIPT>();
        }
    
        public int ID_COMMODITIES_PROVIDER { get; set; }
        public string NAME_COMMODITIES_PROVIDER { get; set; }
        public int DEBT_COST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_COMMODITIES_RECEIPT> IMPORT_COMMODITIES_RECEIPT { get; set; }
    }
}
