//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int ID_CUSTOMER { get; set; }
        public string NAME_CUSTOMER { get; set; }
        public string PHONE_NUMBER_CUSTOMER { get; set; }
        public bool IS_DELETED { get; set; }
        public int DEBT_COST { get; set; }
    }
}
