//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_PAYMENT_RECEIPT_DETAIL_USED_PITCH
    {
        public int ID_RECEIPT_DETAIL_USED_PITCH { get; set; }
        public int ID_CUSTOMER_PAYMENT_RECEIPT { get; set; }
        public int ID_BOOKING { get; set; }
        public string TOTAL_COST_USED_PITCH { get; set; }
    
        public virtual BOOKING BOOKING { get; set; }
        public virtual CUSTOMER_PAYMENT_RECEIPT CUSTOMER_PAYMENT_RECEIPT { get; set; }
    }
}
