//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_PAYMENT_RECEIPT_DETAIL_COMMODITIES
    {
        public int ID_RECEIPT_DETAIL_COMMODITIES_SERVICE { get; set; }
        public int ID_CUSTOMER_PAYMENT_RECEIPT { get; set; }
        public int ID_COMMODITIES { get; set; }
        public int QUANTITY { get; set; }
        public string TOTAL_COST_ACCOMPANIED_SERVICE { get; set; }
    
        public virtual COMMODITy COMMODITy { get; set; }
    }
}
