//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPORT_COMMODITIES_RECEIPT_DETAIL
    {
        public int ID_EXPORT_COMMODITIES_RECEIPT { get; set; }
        public int ID_EXPORT_COMMODITIES_RECEIPT_DETAIL { get; set; }
        public Nullable<int> ID_COMMODITIES { get; set; }
        public Nullable<int> QUANTITY_EXPORT { get; set; }
        public string TOTAL_COST { get; set; }
    
        public virtual COMMODITy COMMODITy { get; set; }
        public virtual EXPORT_COMMODITIES_RECEIPT EXPORT_COMMODITIES_RECEIPT { get; set; }
    }
}
