//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORT_COMMODITIES_RECEIPT_DETAIL
    {
        public int ID_IMPORT_COMMODITIES_RECEIPT_DETAIL { get; set; }
        public int ID_IMPORT_COMMODITIES_RECEIPT { get; set; }
        public int ID_COMMODITIES { get; set; }
        public int QUANTITY_IMPORT { get; set; }
        public string TOTAL_COST { get; set; }
    
        public virtual COMMODITy COMMODITy { get; set; }
        public virtual IMPORT_COMMODITIES_RECEIPT IMPORT_COMMODITIES_RECEIPT { get; set; }
    }
}
