//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINK_PITCH_DETAILS
    {
        public int ID_LINK_PITCH_DETAILS { get; set; }
        public int ID_PARENT_PITCH { get; set; }
        public int ID_CHILDREN_PITCH { get; set; }
    
        public virtual PITCH PITCH { get; set; }
        public virtual PITCH PITCH1 { get; set; }
    }
}
