//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PITCHMANAGEMENTDBEntities : DbContext
    {
        public PITCHMANAGEMENTDBEntities()
            : base("name=PITCHMANAGEMENTDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOKING> BOOKINGs { get; set; }
        public virtual DbSet<COMMODITy> COMMODITIES { get; set; }
        public virtual DbSet<COMMODITIES_PROVIDER> COMMODITIES_PROVIDER { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CUSTOMER_PAYMENT_RECEIPT> CUSTOMER_PAYMENT_RECEIPT { get; set; }
        public virtual DbSet<CUSTOMER_PAYMENT_RECEIPT_DETAIL_COMMODITIES> CUSTOMER_PAYMENT_RECEIPT_DETAIL_COMMODITIES { get; set; }
        public virtual DbSet<CUSTOMER_PAYMENT_RECEIPT_DETAIL_USED_PITCH> CUSTOMER_PAYMENT_RECEIPT_DETAIL_USED_PITCH { get; set; }
        public virtual DbSet<IMPORT_COMMODITIES_RECEIPT> IMPORT_COMMODITIES_RECEIPT { get; set; }
        public virtual DbSet<IMPORT_COMMODITIES_RECEIPT_DETAIL> IMPORT_COMMODITIES_RECEIPT_DETAIL { get; set; }
        public virtual DbSet<LINK_PITCH_DETAILS> LINK_PITCH_DETAILS { get; set; }
        public virtual DbSet<PITCH> PITCHes { get; set; }
        public virtual DbSet<PITCH_TYPE> PITCH_TYPE { get; set; }
        public virtual DbSet<USER_ROLES> USER_ROLES { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    }
}
