//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class PITCH_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PITCH_TYPE()
        {
            this.PITCHes = new HashSet<PITCH>();
        }
    
        public int ID_PITCH_TYPE { get; set; }
        public string NAME_PITCH_TYPE { get; set; }
        public int CREATE_BY_ID_USER { get; set; }
        public Nullable<int> UPDATE_BY_ID_USER { get; set; }
        public string PRICE { get; set; }
        public bool IS_DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PITCH> PITCHes { get; set; }
    }
}
