//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class PITCH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PITCH()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.LINK_PITCH_DETAILS = new HashSet<LINK_PITCH_DETAILS>();
            this.LINK_PITCH_DETAILS1 = new HashSet<LINK_PITCH_DETAILS>();
        }
    
        public int ID_PITCH { get; set; }
        public string NAME_PITCH { get; set; }
        public int PITCH_TYPE_ID { get; set; }
        public int CREATE_BY_ID_USER { get; set; }
        public System.DateTime CREATE_AT { get; set; }
        public Nullable<int> UPDATE_BY_ID_USER { get; set; }
        public Nullable<System.DateTime> UPDATE_AT { get; set; }
        public bool IS_DELETED { get; set; }
        public bool IS_USING { get; set; }
        public bool IS_CHILDREN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK_PITCH_DETAILS> LINK_PITCH_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK_PITCH_DETAILS> LINK_PITCH_DETAILS1 { get; set; }
        public virtual PITCH_TYPE PITCH_TYPE { get; set; }
        public virtual USER USER { get; set; }
        public virtual USER USER1 { get; set; }
    }
}
