//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.PitchManagementTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.BOOKINGs1 = new HashSet<BOOKING>();
            this.CUSTOMER_PAYMENT_RECEIPT = new HashSet<CUSTOMER_PAYMENT_RECEIPT>();
            this.CUSTOMER_PAYMENT_RECEIPT1 = new HashSet<CUSTOMER_PAYMENT_RECEIPT>();
            this.IMPORT_COMMODITIES_RECEIPT = new HashSet<IMPORT_COMMODITIES_RECEIPT>();
            this.IMPORT_COMMODITIES_RECEIPT1 = new HashSet<IMPORT_COMMODITIES_RECEIPT>();
            this.PITCHes = new HashSet<PITCH>();
            this.PITCHes1 = new HashSet<PITCH>();
        }
    
        public int ID { get; set; }
        public string FULL_NAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public bool IS_DELETED { get; set; }
        public int ID_ROLE_NAME { get; set; }
        public Nullable<int> CREATE_BY_ID_USER { get; set; }
        public Nullable<int> UPDATE_BY_ID_USER { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOKING> BOOKINGs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PAYMENT_RECEIPT> CUSTOMER_PAYMENT_RECEIPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMER_PAYMENT_RECEIPT> CUSTOMER_PAYMENT_RECEIPT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_COMMODITIES_RECEIPT> IMPORT_COMMODITIES_RECEIPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMPORT_COMMODITIES_RECEIPT> IMPORT_COMMODITIES_RECEIPT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PITCH> PITCHes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PITCH> PITCHes1 { get; set; }
        public virtual USER_ROLES USER_ROLES { get; set; }
    }
}
