CREATE DATABASE PITCHMANAGEMENTDB;
USE PITCHMANAGEMENTDB;



CREATE TABLE USER_ROLES
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ROLE_NAME VARCHAR(20) NOT NULL,
	IS_DELETED BIT NOT NULL DEFAULT 0,
);

CREATE TABLE USERS
(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	FULL_NAME varchar(100) NOT NULL,
	USERNAME varchar(20) NOT NULL,
	PASSWORD varchar(256) NOT NULL,
	IS_DELETED BIT NOT NULL DEFAULT 0,
	ID_ROLE_NAME INT NOT NULL

	CONSTRAINT fk_USERS_USER_ROLES
		FOREIGN KEY (ID_ROLE_NAME)
		REFERENCES USER_ROLES(ID)
);